config/routes.rb
Demo::Application.routes.draw do   
  root "application#index"
  
  get "booth/vote"
  get "booth/single_ballot_verify"
  
  get "election_verifier/verify"
   
  get "/elections/new", to: "elections#new"
  post "/elections/create", to: "elections#create"
  
  get "/elections/:id", to: "elections#show"
  get "/elections/:id/voters", to: "elections#voters"
  get "/elections/:id/ballots", to: "elections#ballots"
  get "/elections/:id/ballots/:voter_uuid/last", to: "elections#ballots_of_voter"
  get "/elections/:id/result", to: "elections#result"
  get "/elections/:id/trustees", to: "elections#trustees"
  
  post "elections/:id/authenticate", to: "elections#authenticate"
  post "elections/:id/cast_vote", to: "elections#cast_vote"
  
  get "elections/:id/bulletin_board", to: "elections#bulletin_board"
  
  

end

app/controllers/booth_controller.rb
class BoothController < ApplicationController
  def vote
    render :layout => false
  end
  
  def single_ballot_verify
    render :layout => false
  end
end

app/views/booth/single_ballot_verify.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8" /> 
  <title>Voting System</title>
  <%= stylesheet_link_tag "booth/booth.css", media: "all" %>
  <%= stylesheet_link_tag "booth/forms.css", media: "all" %>
  <%= javascript_include_tag "lib/jscrypto/jsbn.js" %>
  <%= javascript_include_tag "lib/jscrypto/jsbn2.js" %>
  <%= javascript_include_tag "lib/jscrypto/sjcl.js" %>
  <%= javascript_include_tag "lib/underscore-min.js" %>
  <%= javascript_include_tag "lib/jquery-1.2.2.min.js" %>

  <%= javascript_include_tag "lib/jquery-jtemplates.js" %>
  <%= javascript_include_tag "lib/jquery.json.min.js" %>
  <%= javascript_include_tag "lib/jquery.query-2.1.5.js" %>

  <script language="javascript">
    // required for jscrypto library
    var JSCRYPTO_HOME = document.location.pathname.replace("<%=booth_single_ballot_verify_path %>", "<%= asset_path 'lib/jscrypto' %>");
  </script>

  <%= javascript_include_tag "lib/jscrypto/class.js" %>
  <%= javascript_include_tag "lib/jscrypto/bigint.js" %>
  <%= javascript_include_tag "lib/jscrypto/random.js" %>
  <%= javascript_include_tag "lib/jscrypto/elgamal.js" %>
  <%= javascript_include_tag "lib/jscrypto/sha1.js" %>
  <%= javascript_include_tag "lib/jscrypto/sha2.js" %>
  <%= javascript_include_tag "lib/jscrypto/helios.js" %>
  <%= javascript_include_tag "booth/verifier.js" %>
</head>
<body>
<script language="javascript">
$(document).ready(function() {
    BigInt.setup(function() {
       $('#verifier_loading').hide();

       if (BigInt.is_dummy) {
          $('#dummy_bigint').show();
          return;
       }

       $('#verifier').show();
       var election_url = $.query.get('election_url');
       $('#election_url').val(election_url); 
    }, function() {
       $('#dummy_bigint').show();
    });
});    

function result_append(str) {
    $('#results').append(str).append("<br />");
}

function verify_single_ballot(election_url, audit_trail) {
  var encrypted_vote_json = jQuery.secureEvalJSON(audit_trail);
  
  result_append("loading election...");

  // quick and dirty detection of cast ballot
  if (encrypted_vote_json['cast_at']) {
    result_append("\n\nIt looks like you are trying to verify a cast ballot. That can't be done, only audited ballots can be verified.");
    return;
  }
  
  $('#loading').show();
  
  var after_computation = function(overall_result) {
    result_append("<br />");
    
    $('#loading').hide();
    
    if (overall_result) {
       result_append('SUCCESSFUL VERIFICATION, DONE!');
    } else {
       result_append('PROBLEM - THIS BALLOT DOES NOT VERIFY.');        
    }
  };

  // the hash will be computed within the setup function call now
  $.ajax({url: election_url, success: function(raw_json) {
    if (window.Worker) {
      var verifier_worker = new window.Worker("<%= asset_path 'booth/verifierworker.js' %>");
      verifier_worker.onmessage = function(event) {
        if (event.data.type == 'log')
          return console.log(event.data.msg);
       
        if (event.data.type == 'status')
          return result_append(event.data.msg);

        if (event.data.type == 'result')
          return after_computation(event.data.result);
      };

      verifier_worker.postMessage({'type':'verify', 'election':raw_json, 'vote':encrypted_vote_json});
    } else {
      var overall_result = verify_ballot(raw_json, encrypted_vote_json, result_append);
      after_computation(overall_result);
    }
  }, error: function() {
      result_append('PROBLEM LOADING election. Are you sure you have the right election URL?<br />');

      $('#loading').hide();
      
      result_append('PROBLEM - THIS BALLOT DOES NOT VERIFY.');        
  }
  });
}

</script>
</head>
<body>
<div id="wrapper">
<div id="banner">
    Single-Ballot Verifier
</div>
<div id="content">

<div id="verifier_loading">
Loading verifier...
</div>

<div id="dummy_bigint" style="display:none;">
Your browser does not have the Java plugin installed.<br /><br />
At this time, the Java plugin is required for browser-based ballot auditing, although it is not required for ballot preparation.
</div>

<div id="verifier" style="display:none;">
<p style="font-size: 16pt;">
    This single-ballot verifier lets you enter an audited ballot<br />and verify that it was prepared correctly.
</p>

<form onsubmit="try {verify_single_ballot(this.election_url.value, this.audit_trail.value);} catch (e) {E = e;} return false;">
Enter the Election URL:
    <input type="text" size="50" name="election_url" id="election_url" /><br />

<p>
Your Ballot:
</p>

<textarea name="audit_trail" cols="80" rows="7">
</textarea><br /><br />
<input type="submit" class="pretty" value="Verify" />
</form>

<br /><br />
<div id="results">
</div>
<%= image_tag "booth/loading.gif", :style => "display:none;" %>
</div>
</div>

</div>

<div id="applet_div">
</div>
</body>
</html>